apiVersion: v2
name: weaviate-operator
description: Kubernetes operator for managing Weaviate clusters with auto-scaling and cloud optimizations
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - weaviate
  - vector-database
  - operator
  - kubernetes
  - cloud-native
home: https://github.com/weaviate/weaviate
sources:
  - https://github.com/weaviate/weaviate
maintainers:
  - name: Weaviate Team
    email: hello@weaviate.io
